name: "Deploy to WordPress.org"

on:
  pull_request:
    branches:
      - develop
  release:
    types: [ prereleased, published ]

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer

      - name: Install dependencies
        run: |
          echo "GitHub event pre-release: ${PRE_RELEASE}"
          echo "Updating composer and NPM"
          composer update --no-dev --optimize-autoloader
          npm install --only=production
        env:
          PRE_RELEASE: ${{ github.event.release.prerelease }}

#      - name: WordPress Plugin Deploy
#        if: "!github.event.release.prerelease"
#        uses: 10up/action-wordpress-plugin-deploy@stable
#        with:
#          generate-zip: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
#          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
#          SLUG: custom-login

#      - name: Upload release asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ${{github.workspace}}/custom-login.zip
#          asset_name: custom-login.zip
#          asset_content_type: application/zip
