name: "Deploy to WordPress.org"

on:
  release:
    types: [ published ]

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run composer install
        run: |
          composer install --no-interaction --optimize-autoloader

      - name: Run composer update
        run: |
          composer update --no-dev --no-interaction --optimize-autoloader

      - name: Set Node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run npm install
        run: |
          npm install --only=production
        env:
          PRE_RELEASE: ${{ github.event.release.prerelease }}

      - name: Test release condition
        if: |
          github.event_name == 'release' && !github.event.release.prerelease
        run: echo "Success this is a prerelease ${{ github.event.release.prerelease }}"

#      - name: WordPress Plugin Deploy
#        if: |
#          ${{ github.event_name == 'release' && !github.event.release.prerelease }}
#        uses: 10up/action-wordpress-plugin-deploy@stable
#        with:
#          generate-zip: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
#          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
#          SLUG: custom-login

#      - name: Upload release asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ github.event.release.upload_url }}
#          asset_path: ${{github.workspace}}/custom-login.zip
#          asset_name: custom-login.zip
#          asset_content_type: application/zip
